### ISSUE TITLE
Storybook html-lie-component-html 문서 오타 제보

### ISSUE THREAD

**Issue by HanSeo0507** [HyunsDev/opize-design-system#28]
안녕하세요, 스토리북 문서를 보다가 오타 내용이 있는 것 같아서 제보드립니다!

스토리북 [html-like-component-html](https://design.opize.me/?path=/story/html-like-component-html-like-component--page) 문서 테이블에 `<Title>: <j1>, <h2>, <h3>` 라고 되어 있는데, `h1` 태그를 잘못 입력하신 것 같아요

<img width="454" alt="스크린샷 2022-09-10 오전 5 51 03" src="https://user-images.githubusercontent.com/56479293/189442122-1e2a388b-6994-401a-a72f-f328886e9071.png">

**Comment by HyunsDev** [comment]
26046b0 에서 수정했습니다!
라이브러리에 큰 영향을 주는 버그는 아닌 것으로 생각되어 다음 업데이트 (v0.14.0 또는 v0.13.1)에 함께 배포하겠습니다

감사합니다 :)
